version: '3'

services:
  app:
    build: .
    container_name: svn-ifsvnadmin
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - svnadmin_data:/var/www/html/svnadmin/data
      - svn:/var/www/svn
      - httpd_log:/var/log/httpd
      - httpd_conf.d:/etc/httpd/conf.d
      - httpd_ssl:/etc/pki/svnadmin

volumes:
  svnadmin_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /var/svn_svnadmin/svnadmin_data
  svn:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /var/svn_svnadmin/svn
  httpd_log:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /var/svn_svnadmin/httpd_log
  httpd_conf.d:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /var/svn_svnadmin/httpd_conf.d
  httpd_ssl:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /var/svn_svnadmin/httpd_ssl

